name = "SRO"
uuid = "51442a77-0e55-4fa2-ad6a-e629eb677da6"
authors = ["Jens Sager <jens.sager@uni-oldenburg.de>"]
repo = "https://github.com/jsagerOffis/SRO"
version = "0.1.0"

[deps]
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]